baseUrl: "http://www.nnfcxx.com/vipdata/fcj.php?list=xjspf&ctg=0&gsmc="
httpConnectTimeout: 100000
httpReadTimeout:  100000
httpWriteTimeout:  100000
httpMethod:  POST
#httpHeader:
#httpPostParams:
#httpBody: "<PDoc Tag='GetYSPrjInfo' />"
basePagingTaskNum: 1
basePageStart: 1
basePageEnd: -1 #less than 0 means end is tatal pages
basePageUrl: "http://www.nnfcxx.com/vipdata/fcj.php?list=xjspf&ctg=0&gsmc=&page=[PAGENO]"
basePageInfoType: HTML_ELE_EXTRAT
basePageInfoPatternStr: (\\d+)é¡µ
basePageInfoSelector: "#AspNetPager1 > table > tbody > tr > td:nth-child(1)"