baseUrl: http://www.xzsfdc.com/shangpflist.aspx
httpConnectTimeout: 100000
httpReadTimeout:  100000
httpWriteTimeout:  100000
httpMethod:  GET
#httpHeader:
#httpPostParams:
#httpBody:
basePagingTaskNum: 1
basePageStart: 1
basePageEnd: -1 #less than 0 means end is tatal pages
basePageUrl: "http://www.xzsfdc.com/shangpflist.aspx"
basePageInfoType: HTML_ELE_EXTRAT
basePageInfoPatternStr: (\\d+)é¡µ
basePageInfoSelector: "#AspNetPager1 > table > tbody > tr > td:nth-child(1)"