baseUrl: http://61.142.120.214:9000/web/nowonsale.jsp
httpConnectTimeout: 100000
httpReadTimeout:  100000
httpWriteTimeout:  100000
httpMethod:  GET
#httpHeader:
#httpPostParams:
#httpBody:
basePagingTaskNum: 1
basePageStart: 1
basePageEnd: -1 #less than 0 means end is tatal pages
basePageUrl: "http://61.142.120.214:9000/web/nowonsale.jsp"
basePageInfoType: HTML_ELE_EXTRAT
basePageInfoPatternStr: å…±(\\d+)é¡µ
basePageInfoSelector: "#Searchresults > table > tbody > tr:last-child > td"
